//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 11:55:19 PM CET 
//


package t3.toe.domains.bw6.domains;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteDomainWhenNotExistsBehaviour.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="deleteDomainWhenNotExistsBehaviour"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="fail"/&gt;
 *     &lt;enumeration value="skip"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "deleteDomainWhenNotExistsBehaviour")
@XmlEnum
public enum DeleteDomainWhenNotExistsBehaviour {

    @XmlEnumValue("fail")
    FAIL("fail"),
    @XmlEnumValue("skip")
    SKIP("skip");
    private final String value;

    DeleteDomainWhenNotExistsBehaviour(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeleteDomainWhenNotExistsBehaviour fromValue(String v) {
        for (DeleteDomainWhenNotExistsBehaviour c: DeleteDomainWhenNotExistsBehaviour.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
