//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.01 at 03:20:25 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://teecu.be/toe-domains/bw6-domains", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package t3.toe.domains.bw6.domains;
